### ISSUE TITLE
Push/mail notifications for new aired episodes

### ISSUE THREAD

**Issue by onlytanmoy** [JumBay/wako#10]
First things first, many thanks for this awesome app.
I have a request on the below feature of the app
- Be notified on new aired episodes

Please can you enable push notifications for the new aired episodes and/or email notifications?

**Comment by JumBay** [comment]
If you've enabled notifications in settings, you should be notified by new aired episode via push notification, not by email thought (I don't know user's email)

**Comment by onlytanmoy** [comment]
Hmm.. That's weird coz both notification options under wako settings are enabled.. Still no luck getting push notifications. 
Also do you plan to make wako available for Win 10 platform?

**Comment by JumBay** [comment]
If you check "Be only notified for my next up to watch episodes", you'll only be notified if you have watched everything and then a new episode aired. Maybe I should make it clearer. 

Why do you want to it to be available on desktop?

**Comment by onlytanmoy** [comment]
Yes, thats exactly what I want to be notified of. Say the last episode of Supernatural was aired on 22/03, I am yet to watch that, so I should get a notification in that case.
Just had the version updated to v1.5.5, when I now go to Home page in wako, it says 'Nothing to watch' under 'Up Next to watch' :(
I did try clear app cache, logout and re-login, still the same issue.
And the reason i asked for a desktop version is because when at home I spend more time in my Win 10 laptop than mobile...so i was checking with you on the possibility of a windows version.

**Comment by JumBay** [comment]
Trakt server is sometimes overloaded, if you try a bit later your shows should come back.
Ok I see, but for now it's not in the roadmap. Btw on which device do you use Kodi?

**Comment by onlytanmoy** [comment]
I am using a simple LeEco Le2 android mobile. Don't bother spending time on this for all i know may be I am alone not getting the push notification.
Yeh, Trakt server does have that problem at time, so that explains the missing shows.
Using Kodi Leia on MiBox 3.

**Comment by onlytanmoy** [comment]
Looks like some major issue at Trakt end..i am now getting the below message
Trakt API-failed to load resource, please try again later (err code undefined)

**Comment by onlytanmoy** [comment]
Up Next to Watch shows nothing in Wako...pls see screenshots from both Wako & Trakt
Tried clearing cache, logout, re-login...nothing helped.
![Screenshot_wako_20190326-200037](https://user-images.githubusercontent.com/48493659/55029445-fbba7100-5001-11e9-91f2-f782da140618.png)
![Screenshot_1](https://user-images.githubusercontent.com/48493659/55029525-302e2d00-5002-11e9-9b52-b1a19d39fbda.png)

**Comment by JumBay** [comment]
Hum did you get any alert in wako about trakt not working? 
This can happen within 2 conditions:
- Trakt is unreachable (but I should handle this case)
- Trakt doesn't send me any next episode to watch. Which already happened to me, but they have some bugs in their API.

When you go in "My TV Shows" do you see shows with blue badge saying you have episode to watch? 

Btw do you still have the notifications issues? I've tried on android and ios and both had worked.

**Comment by onlytanmoy** [comment]
Ok, seems like it was an intermittent issue. Up next to watch is now populated in Wako. 
And yes still having the notification issue but possibly for my device alone as you have tested successful working of the same. Closing this issue. Thanks mate. 
![Screenshot_wako_20190327-132507](https://user-images.githubusercontent.com/48493659/55079698-98c5ea00-5094-11e9-8351-f2330c6d8bdb.png)
