### ISSUE TITLE
IMDb watchlist section inclusion

### ISSUE THREAD

**Issue by onlytanmoy** [JumBay/wako#11]
Can you please integrate IMDb with the Wako app? Like a separate section say 'My IMDb'.

Thing is not all my regional movies/shows are available in Trakt but are present in IMDb and hence added to my IMDb watchlist.
So, if you consider this request then I can access my IMDb watchlist via Wako app. Thanks.

**Comment by JumBay** [comment]
Sorry but IMDb doesn’t provide any API. Can you find your medias on https://www.themoviedb.org or https://www.thetvdb.com/ ?

**Comment by onlytanmoy** [comment]
Oh...i see...and yes I just tried out now...i am able to find all the 3 TV shows in https://www.themoviedb.org
These are not available in Trakt.

**Comment by JumBay** [comment]
Good you should then contact trakt and ask them to add the shows/movies. If it’s not on trakt it couldn’t be sync
