### ISSUE TITLE
Enable VPN warning message

### ISSUE THREAD

**Issue by onlytanmoy** [JumBay/wako#12]
Please can you include a banner message saying 'Remember to enable VPN' after launching the Wako app? The other day after streaming a torrent in Elementum I realised that I forgot to switch on VPN in my MiBox..lol.

**Comment by JumBay** [comment]
Sorry but you don’t need any vpn to use wako. Wako is not responsible if you use illegal sources

**Comment by onlytanmoy** [comment]
As I understand Wako is a nice interface to use the Elementum add-on in Kodi. You might know in some countries you do need to enable VPN while streaming torrents via Elementum and that's why I proposed this you see mate :)
