### ISSUE TITLE
Wako>OpenMeta for TV shows does not work

### ISSUE THREAD

**Issue by SoulTV** [JumBay/wako#13]
Wako>OpenMeta for TV shows does not work

Reddit post explaining: https://www.reddit.com/r/Addons4Kodi/comments/bhncqr/wako_is_now_compatible_with_seren_gaia_and_other/eluk922?utm_source=share&utm_medium=web2x

Hope this helps, love the app. Thx!

**Comment by SerpentDrago** [comment]
As seen in the thread , i confirm this issue

**Comment by JumBay** [comment]
I’ll look into it in next 2 days

**Comment by JumBay** [comment]
If you have android, could you please try the new beta version and confirm it all works: https://play.google.com/apps/testing/app.wako
Thanks

**Comment by JumBay** [comment]
It's fixed
