### ISSUE TITLE
Access your lists from Trakt

### ISSUE THREAD

**Issue by ProZeeshan** [JumBay/wako#15]
That would be an awesome feature!

I follow some lists on Trakt like "Latest Releases". I want to see that list in my Wako app so I can select the movie and watch from there.

**Comment by JumBay** [comment]
Could you please give me the link of this list, like that I'll have a real example. Thx

**Comment by ProZeeshan** [comment]
https://trakt.tv/users/garycrawfordgc/lists/latest-releases?sort=added,asc

Here is the list I use. It is a public list. To follow list as a free user you just like the list and it will show up in your profile under public lists.

**Comment by JumBay** [comment]
done
