### ISSUE TITLE
Search Source Manually - Manual bookmarks

### ISSUE THREAD

**Issue by onlytanmoy** [JumBay/wako#20]
In Movies & TV Shows sections, for 'Search Source Manually' feature, pls provide an option to bookmark the search results so that I can access all such bookmarked results at a later time without having to trigger the same manual search and more importantly scroll through all search results to find that particular stream. This becomes greatly helpful when a show has got several episodes (see image below), where each day I plan to watch one episode from a specific working link.
You can create a section like 'Manual Bookmarks' under Settings to implement this feature. Thanks.
![IMG_20190507_193107](https://user-images.githubusercontent.com/48493659/57329033-d6457a80-710a-11e9-955c-faea8ca49e4e.jpg)

**Comment by JumBay** [comment]
Why do you use manual source for those shows?

**Comment by onlytanmoy** [comment]
These Indian web series/shows are not available on Trakt. Absent in RD too, so even though I got a premium RD account, it doesn't help. That's why I rely on 'Search Source Manually' feature of wako to fetch the stream from the providers list. Can you enable a star icon to bookmark the working links so that next time I can spot them from 'Manual bookmarks' section?

**Comment by JumBay** [comment]
Sorry but this requires a lot a work to store all of this for what I think a too specific request. Maybe I'll do it in the future, but not now. It mays be better to ask trakt to add the shows on their database.

**Comment by onlytanmoy** [comment]
Ok.. i will wait for a future update to cater my request.
