### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by dxfan227** [JumBay/wako#21]
Cool app!

1. Be able to get to full series info from individual episode page
2 on iPhone XS Max is you click on an image the X is in the menus bar and now clickable ( id just turn off clickable images all together)
3 pull to refresh on my shows/movies page

**Comment by JumBay** [comment]
Thanks!

1. Which information do you want?
2. I’ll fix it in the next release
3. I’ll look into it

**Comment by dxfan227** [comment]
@JumBay  for example if you go to tv shows > game of thrones....the page you are on is the series overview and includes all seasons/episodes........in the "home" section, you have a list of your tv shows that need to be watched, if I click on game of thrones season 8 episode 3.....I get taken to an outline of that episode....there should be a link on this page to " View Full Series" to take me to the full series page. Make sense?

Also on iphone xs max 12.1.1 Beta 3 on the "home" screen there is no artwork next to episodes.

**Comment by JumBay** [comment]
1. Yes these pages must be improved with characters list... too

I’ll look into this for the next update

**Comment by dxfan227** [comment]
@JumBay also it seems that from a series page you can hit the eyeball to remove from watched list....but there is no eyeball to add back to watch list

**Comment by dxfan227** [comment]
@JumBay  Also, the home page isnt 100 percent up to date  IE tongiht lucifer airs but it's not in my home page. This might be an issue with the way trakt handles timing ( all UTC) here is a quick blurb on how to maybe fix this.

> 
> So I spent a little while/a few iterations working this out, but my previous comment covers the general solution. As a broken down example to explain, check out the /calendars/all/shows endpoint.
> 
> The first result will generally have a first_aired timestamp of something like 2019-04-26T00:00:00.000Z, where the 00:00:00.000Z is 00:00 UTC because the date used for the results is in UTC (as with like 99% of the dates you send/receive using the API).
> 
> So if your local Timezone is something other than UTC (GMT+0), you need to account for that offset when converting your expected start date to UTC and using that as your start_date, and using the days parameter to make up the difference of the offset in order to pick up anything outside the offsets.
> 
> Using 26 April 2019 as an example day:
> If your Timezone is GMT+10, you’ll want to use pretty much the day before, as 2019-04-26 00:00 GMT+10 is 2019-04-25 14:00 GMT+0. So the start_date parameter you want is 2019-04-25. However because that will return results from 2019-04-25 00:00 to 23:59 GMT+0, you also need to add one day in total in order to receive up to 2019-04-26 14:00 GMT+0, so the days parameter you want is 2. Meaning your endpoint is /calendars/all/shows/2019-04-25/2.
> 
> Now, you’ll receive items from 2019-04-25 00:00 GMT+0 to 2019-04-26 23:59 GMT+0. This means in order to get only the items from those results that fall within your original start/end date (2019-04-26 00:00 to 23:59 GMT+10), you need to filter out all the items outside those times.
> 
> For a negative GMT (eg. GMT-8), you do the same, pretty much (logic is exactly the same), but for the sake of the example, you’re going the other way (basically, start_date is 2019-04-26 and still using days parameter of 2 to make up the difference, seeing as 2019-04-26 00:00 GMT-8 is 2019-04-26 08:00 GMT+0 meaning you need to get up to 2019-04-27 08:00 GMT+0. You should end up with items between 2019-04-26 00:00 GMT+0 and 2019-04-27 23:59 GMT+0. Once again you’re going to need to filter out anything outside 2019-04-26 00:00 to 23:59 GMT-8.
> 
> I’m unsure if I can explain it any better than that heh. The important thing is that the dates you use for the endpoint are in UTC, hence why for GMT+10 you’re technically using the day before through to the day you’re in, and for GMT-8 you’re using the day you’re in through to the next day. This would be why you’re seeing somewhat “correct” results when using tomorrow’s date and seeing some of tomorrow’s results, but you’ll find it’s also including some of the day before/after as well due to the UTC logic. Using the all endpoint is likely the best way to test as it should have items ranging from 00:00 to 23:59 in any time zone (although also has a lot of items for each request lol).


Also I use another trakt app for use in my magic mirror application. This developer seems very strong with the trakt api, you may want to know about him if you need any help in the future? https://github.com/Kiina/MMM-trakt

**Comment by JumBay** [comment]
If you want to remove a tv shows from your watch list you have to hit the bin button or mark all episodes as unwatched. To add a tv show to your watchlist, just mark at least one episode as watched. That’s how trakt works. 

For the up next to watch filter it might be a cache issue. Could you please try to clear wako cache and try again (In wako Settings > Clear Cache then restart the app)?

**Comment by dxfan227** [comment]
Cleared the cache. 

Still doesn’t show Lucifer I’ll keep an eye on it.

**Comment by dxfan227** [comment]
@JumBay

Any ideas why the app on my phone has no photos but my wife’s does? Same phone same carrier 

https://imgur.com/gallery/kpe5Aas

**Comment by JumBay** [comment]
if you do scroll the list, do you have images?

**Comment by dxfan227** [comment]
No

**Comment by JumBay** [comment]
which ios version do you have?

**Comment by dxfan227** [comment]
12.1.1 Beta 3

**Comment by JumBay** [comment]
Version 2.1.5 is out, update your app, it should fix some of these issues

**Comment by dxfan227** [comment]
Will do.

Maybe you can help me understand something about trakt. So I have upcomming
shows ( this show in the calendar on the main page and is based on my watch
list) but I also have a progress area....this is what I see in wako....so
if I have a show on my watchlist that I havent watched yet......it will
show in upcoming calender but not in progress. Is there any way to get the
watchlist and progress to be the same?

Thanks,

David B. Ruiz |
*Director of Recruitment**G*
*lobal Talent Solutions, Inc.**Email:* druiz@gtsrecruiters.com
*Office:* 714-921-6428 x. 307
*Mobile:* (408) 641-9701
*Web:* http://www.GTSrecruiters.com <http://www.gtsrecruiters.com/>

**Comment by JumBay** [comment]
Hi, 
How do you add this show on your calendar? For now, the up next to watch is based only on your watch in progress, so if you've never watched at least one episode it won't be listed

**Comment by dxfan227** [comment]
I just added it to my watch list.....this will show the episodes on the "
upcomming calendlar" but does not show it under progress ( which is what
wako looks at) sometimes trakt is overly complicated

Thanks,

David B. Ruiz |
*Director of Recruitment**G*
*lobal Talent Solutions, Inc.**Email:* druiz@gtsrecruiters.com
*Office:* 714-921-6428 x. 307
*Mobile:* (408) 641-9701
*Web:* http://www.GTSrecruiters.com <http://www.gtsrecruiters.com/>

**Comment by JumBay** [comment]
watchlist for shows is not handled yet
