### ISSUE TITLE
Honor 3c White screen

### ISSUE THREAD

**Issue by ArsalanAlli** [JumBay/wako#22]
Hello, I have installed the latest version of the app. When i launch the app, after logo app freezes with all white screen and i have to kill the app. 
My Phone model is Huawei Honor 3C with 4.4.2.

I have installed this app on my Wife's honor 7x and it is working fine.
I would be greatful if this gets resolved.

Thanx

**Comment by JumBay** [comment]
Hello,

Sorry but wako is not compatible with android < 7. I tried but I encounter too many bugs. I'll have to see why it says compatible with Android 4.4 on the play store

**Comment by ArsalanAlli** [comment]
Yeah that's what i was thinking when i downloaded the app cuz it said it needs 4.4.
Thanks for the reply btw :)
