### ISSUE TITLE
Dynamic/Auto update of providers?

### ISSUE THREAD

**Issue by onlytanmoy** [JumBay/wako#25]
Will it be possible in Wako to **auto update saved providers** from a defined pastebin URL (say the one from davidreed as David keeps on updating the providers sources) much like how Seren auto updates its a4kscraperpack providers in Kodi?

**Comment by JumBay** [comment]
I'll do it in a future release

**Comment by onlytanmoy** [comment]
Thanks bud... that will be smashing 👍

**Comment by JumBay** [comment]
done

**Comment by onlytanmoy** [comment]
thanks for this one mate...may be you can use the same providers URL concept to tackle #27
