### ISSUE TITLE
New PM cached functionality mainly returning LQ transcode links

### ISSUE THREAD

**Issue by chiefkes** [JumBay/wako#39]
The new premiumize cached option is currently returning premiumize transcoded versions instead of the full quality cached premiumize link. This can be checked by comparing the advertised torrent file size with the size of the download from the Wako Web player

**Comment by JumBay** [comment]
Done, I still use the transcoded version if you wanted to play it on your browser due to the limitation  with mkv files

**Comment by chiefkes** [comment]
What about chromecasting? Is that full definition?

**Comment by JumBay** [comment]
it's gonna be the transcoded one too. I've managed to chromecast HD video that can't be played on the browser, but sometimes I don't have sound...
