### ISSUE TITLE
would be nice to add new providers

### ISSUE THREAD

**Issue by antonsoroko** [JumBay/wako#4]
would be nice to add 
english: thepiratebay and maybe magnetdl as providers
russian: rutor.info and rutracker.org

probably cound be ported from elementum burst/nova providers
https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json
https://github.com/Nemiroff/script.elementum.nova/blob/master/nova/providers/providers.json

**Comment by Nemiroff** [comment]
`{
    "rutor": {
        "name": "RuTor",
        "enabled": true,
        "enabled_in_list": true,
        "languages": ["ru"],
        "base_url": "http://rutor.info/search/0/0/300/2/{query}",
        "response_type": "text",
        "movie": {
            "query": "",
            "keywords": "{title} {year}"        
        },
        "episode": {
            "query": "",
            "keywords": "{title} {episodeCode}"        
        },
        "html_parser": {
            "row": "doc.querySelectorAll('tr.gai, tr.tum')",
            "title": "row.querySelector('td:nth-child(2)').innerText",
            "peers": "row.querySelector('td:nth-child(5) span.green').innerText",
            "seeds": "row.querySelector('td:nth-child(5) span.red').innerText",
            "size": "row.querySelector('td:nth-child(4)').innerText",
            "url": "row.querySelector('td:nth-child(2) a:nth-child(1)').getAttribute('href')"
        }
    }
}`
RuTor

**Comment by antonsoroko** [comment]
@Nemiroff nice work, thanks!

**Comment by Nemiroff** [comment]
Need {season} and {episode}

**Comment by JumBay** [comment]
Can you write an example on how the url should be for an episode?

**Comment by Nemiroff** [comment]
S05-01-13
S05x01
S05 for full season
05x01
Need {season} and {episode}

**Comment by JumBay** [comment]
Done. https://pastebin.com/raw/r7WpcMwR

I added {season} {episode} {titleFirstLetter} and this can be set/replace in the URI directly. I also add separator

**Comment by Nemiroff** [comment]
Can you add some debug info from provider ? Or how i can look why provider not return result?

**Comment by JumBay** [comment]
I think it’s better to debug it on a computer. 
I’ll see what I can do to test a provider easily.

**Comment by JumBay** [comment]
Try that https://github.com/JumBay/wako#test-a-provider

**Comment by JumBay** [comment]
What’s the isssue?
I won’t provide any provider on this repo (for legal reasons ;) )
However if you have any issue making a provider works we can discuss it here

**Comment by antonsoroko** [comment]
I meant to keep this 'issue" (as entity/item) open just to make it easy searchable. That's it :-)

**Comment by JumBay** [comment]
I prefer to keep the repo clean about opening issues. 
If there is some information people should knows about it then it should be added into the readme or in a wiki page. 

Btw I added a debug mode to display eventual error. It’s not the best way to debug a provider but it can help.
