### ISSUE TITLE
Ability to open video from PM/RD in another player

### ISSUE THREAD

**Issue by andycam22** [JumBay/wako#41]
At the moment you have videos open in a browser once you have selected a cached torrent to open in Wako. Is it possible to give an option for opening videos in a player installed on the phone (i.e. VLC) or if not, copy the PM/RD link to the clipboard without URL encoding (as in VLCs case it doesn’t like them) and it can be done manually?  Cheers.

**Comment by JumBay** [comment]
Sure I'll add the option. I know how to do it on iOS, need to it for android too. it will be better than the browser option

**Comment by JumBay** [comment]
VLC support has been added. I won't add other players so far since VLC works very well
