### ISSUE TITLE
notifications about new episodes

### ISSUE THREAD

**Issue by antonsoroko** [JumBay/wako#6]
in the future it would be nice to have notifications about new episodes. In this case your app would be able to replace other trakt clients (https://github.com/SimonVT/cathode/ is a good and simple one, but it was abandoned and thus has some issues. btw, it is open source)

i guess most of apps for trakt does not use server side for notification. simple sync from time to time with trakt - trakt will give you air dates. then notify user when air date is approaching (e.g. in 4 hours).

**Comment by JumBay** [comment]
Done

**Comment by antonsoroko** [comment]
Could you please provide some details about how it works? To understand what to expect.
Also, what is notification time? (Don't know how to put it - I mean amount of time before air time)

**Comment by JumBay** [comment]
Well it get all the shows you’re watching (those in “My shows”) and asks to trakt the next episode for each one (I didn’t find a better way to do that so it can take time). If any I’ll set the given air date as notification trigger date. 
I don’t know exactly if the air date from trakt is accurate especially with different timezone. I could add a setting to be notified before the air date. Just need to see how things work. 
Let’s write feedback here.
