### ISSUE TITLE
Back button works strange

### ISSUE THREAD

**Issue by antonsoroko** [JumBay/wako#7]
Back button (in navbar) works strange in the app, for example - it returns me back to text area that I already saved, or sometimes I can't even exit (like loop).
Thanks.

**Comment by JumBay** [comment]
Ok. I’ll check that. I’m not on android I didn’t test the app that much on this platform. 
Also I’m using ionic 4 framework under the hood which is not a stable release yet so bugs can occur.

**Comment by antonsoroko** [comment]
Just out of curiosity, on what platform you use your app?

**Comment by JumBay** [comment]
On iOS

**Comment by Nemiroff** [comment]
@antonsoroko back button work as back in browser(app is web based)

**Comment by JumBay** [comment]
I fixed it
