### ISSUE TITLE
Kodi remote

### ISSUE THREAD

**Issue by onlytanmoy** [JumBay/wako#9]
Can you pls include the below 2 features in the Kodi remote?
a. Keyboard interface so that I can search for movies/shows etc in the kodi virtual keyboard
b. Feature to paste strings/api keys from android clipboard to the kodi

**Comment by JumBay** [comment]
a. When the virtual keyboard in kodi pops up, it opens a dialog in wako to enter the text you want.
b. should be same as A.
Maybe there is something I don't get it, show me an example. I'll be happy to see if I can implement it

**Comment by onlytanmoy** [comment]
Thanks for your response Jean. I am off to work now. Let me check on this tonight and i shall revert. 
I left a comment in the XDA post on including a particular provider.. any luck with that?

**Comment by JumBay** [comment]
yeah I just answered to it, if it's an illegal source I won't talk about It, sorry

**Comment by onlytanmoy** [comment]
Its like 1337x, rarbg, yts only which are already set as providers here https://pastebin.com/raw/HMNgMtzE
The url is https://movcr.tv
Pls check if it is fine to be added to the provider list or not.

**Comment by onlytanmoy** [comment]
This is all good now...i see the option to enter/paste text into the virtual keyboard of kodi....cheers!
